apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spring-music
  name: spring-music
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-music
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-music
    spec:
      containers:
        - image: kontinue/spring-music
          name: spring-music
          imagePullPolicy: Always
          env:
            - name: JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: 
              value: '{enabled: false}'
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: spring-music
  name: spring-music
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: spring-music
  type: ClusterIP
